"""ESG keyword dictionary loader + sentence matcher.

The dictionary itself lives in `esg_keywords_v2.json`, generated by the
pruning pipeline:

    python -m data_processing.extract_keywords       # → yake_candidates.json
    python -m data_processing.prune_candidates       # → candidates_review.csv
    # ... fill `keep` and `pillar` columns in the CSV ...
    python -m data_processing.compile_dictionary     # → esg_keywords_v2.json

Used as a fast pre-filter: any sentence containing at least one of these
phrases is forwarded to the semantic GRI mapper for finer classification.

Matching is case-insensitive on NFC-normalized text with Vietnamese-aware
word boundaries. Keep entries to multi-word phrases where possible —
single words like "nước" or "khí" produce too many false positives in
financial text.
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path


_DICT_PATH = Path(__file__).resolve().parent / "esg_keywords_v2.json"


def _load_pillar_dict(path: Path) -> dict[str, list[str]]:
    if not path.exists():
        raise FileNotFoundError(
            f"{path.name} not found at {path}. Build it with:\n"
            "  python -m data_processing.extract_keywords\n"
            "  python -m data_processing.prune_candidates\n"
            "  # fill `keep` and `pillar` columns in candidates_review.csv\n"
            "  python -m data_processing.compile_dictionary"
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    by_pillar = payload.get("by_pillar")
    if not isinstance(by_pillar, dict):
        raise ValueError(f"{path.name} is missing the `by_pillar` section")
    return {p: list(kws) for p, kws in by_pillar.items()}


ESG_KEYWORDS: dict[str, list[str]] = _load_pillar_dict(_DICT_PATH)


def _normalize(s: str) -> str:
    return unicodedata.normalize("NFC", s).lower()


def _compile() -> list[tuple[str, str, re.Pattern[str]]]:
    """Return list of (pillar, keyword, compiled_pattern)."""
    out: list[tuple[str, str, re.Pattern[str]]] = []
    for pillar, kws in ESG_KEYWORDS.items():
        for kw in kws:
            kw_n = _normalize(kw)
            pattern = re.compile(
                rf"(?<![\wÀ-ỹ]){re.escape(kw_n)}(?![\wÀ-ỹ])",
                re.IGNORECASE,
            )
            out.append((pillar, kw, pattern))
    return out


_COMPILED = _compile()


def find_matches(sentence: str) -> list[tuple[str, str]]:
    """Return list of (pillar, keyword) hits in `sentence`. Empty if none."""
    sent_n = _normalize(sentence)
    hits: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for pillar, kw, pat in _COMPILED:
        if pat.search(sent_n):
            key = (pillar, kw)
            if key not in seen:
                hits.append(key)
                seen.add(key)
    return hits


def is_esg_candidate(sentence: str) -> bool:
    return bool(find_matches(sentence))
